# Generated by Django 2.0.2 on 2019-04-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
    ]
